### ISSUE TITLE
Problem with FMI Toolbox license

### ISSUE THREAD

**Issue by kasper13** [rimac-technology/med2018-automotive-challenge#3]
Dear Rimac Team,
I contacted Modelon so I could get license to start working with your model,  but they responded to me that they cannot give it to an individual. I will post their response for the sake of clarity 

Hello Miroslav,
Unfortunately we cannot issue licenses to individual students but would have to get this organised centrally at your university. Could you please send me the contact details of somebody at your university who could manage this (professor or lecturer, etc). Alternatively we could issue a license to someone managing the challenge project. Basically – what we cannot do is to issue a license to any individual taking part in the challenge – especially as there is no revenue involved.

Please let me know if you have an idea how we could set this up centrally and I will be happy to help.

Could the license maybe be hosted at RIMAC?

Looking forward to hear from you,

Thomas

Is there anything you can do to resolve this issue, because my faculty also doesn't have license for their toolbox.
Kind regards,
Miroslav Kosanic

**Comment by krunohrvatinic** [comment]
Dear Miroslav,

You do not need a Modelon FMI Toolbox license to use Functional Mockup Units.
If you have Matlab R2017b or later, you can import the FMU as shown in the "solution.slx" file.
If you have an older version of Matlab, you can contact the Mathworks FMI Experts as described in [this Matlab Central answer](https://www.mathworks.com/matlabcentral/answers/181642-can-i-integrate-functional-mockup-units-fmu-with-simulink)

Also, please note that this information is available in the challenge documentation, under "Section 4 - Using the Vehicle Model".

Does this resolve your issue?

Kind regards,
Kruno Hrvatinić

**Comment by kasper13** [comment]
Dear Kruno, 
I contacted Mathworks FMI Experts because my version of Matlab is R2014a.If I may ask, is "solution.slx" just an example of how to import FMU, or is it a shell in which we need to fill Controler part?
Kind regards,
Miroslav Kosanic

**Comment by krunohrvatinic** [comment]
Hi Miroslav,

"solution.slx" is a shell in which you need to fill the Controller part. Once again, refer to the challenge documentation under "Section 5 - Challenge Rules". The examples can be found in the "challenge-resources/examples" folder.

Kind regards,
Kruno Hrvatinić

**Comment by kasper13** [comment]
Dear Kruno, 
Thanks for your quick answers, and thank you for your patience.
Kind regards,
Miroslav Kosanic
